# 基础 http 配置
server:
  name: uniTranslate
  address: "0.0.0.0:9431"
  cacheMode: redis # redis , mem , off 模式 mem 会将翻译结果存储到程序内存中 模式 off 不写入任何缓存
  cachePlatform: false # 执行缓存key生成是否包含平台 (会影响项目启动时自动初始化存储的key)
  cacheRefreshOnStartup: false # 启动时是否从数据库刷新缓存 (会先清除缓存里所有的 缓存 在从数据库逐条初始化 数据 慎用!!!)
  key: "hdasdhasdhsahdkasjfsoufoqjoje" # http api 对接时的密钥
  keyMode: 1 # 模式 1 直接传入 key 做验证 模式 2 使用 key 加密加签数据进行验证
  configDeviceMode: "xdb" # xdb 内置数据库 mysql 使用 MySQL 作为配置存储引擎
  configDeviceMySqlDb: "default" # 翻译配置的数据库设置
  cacheWriteToStorage: false # 是否将缓存写入到数据库
  requestRecordKeepDays: 7 # 请求记录保留天数
  apiEditConfig: false # 是否开启 api 修改配置

# 数据库
database:
  default:
    type: "mysql"
    link: "{user}:{pass}@tcp(127.0.0.1:3306)/{dbname}?charset=utf8mb4&parseTime=true&loc=Local"
    createdAt: "createTime"
    updatedAt: "updateTime"
    debug: true

# redis
redis:
  default:
    address: 127.0.0.1:6379
    db: 0
    pass: ""

# 日志
logger:
  path: "./log/default"
  level: "all"
  stdout: false
  writerColorEnable: true

# GrayLog 支持
grayLog:
  open: false
  host:
  port:
